### ISSUE TITLE
Airplus firmware 73.1 can't connect

### ISSUE THREAD

**Issue by NederBelg** [r1sim/philips-air-to-mqtt#2]
Hi,
I'm setting up the philips-air-to-mqtt. If it works it would be great since IFTTT stopped for the airplus.

I get the following error:

2024-10-26 23:16:22     _currentUrl: 'http://192.168.178.111/di/v1/products/0/security',
2024-10-26 23:16:22     _timeout: null,
2024-10-26 23:16:22     [Symbol(kCapture)]: false
2024-10-26 23:16:22   },
2024-10-26 23:16:22   response: undefined,
2024-10-26 23:16:22   isAxiosError: true,
2024-10-26 23:16:22   toJSON: [Function: toJSON]
2024-10-26 23:16:22 }
2024-10-26 23:16:22 Error while checking filter status Error: connect ECONNREFUSED 192.168.178.111:80
2024-10-26 23:16:22     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
2024-10-26 23:16:22   errno: -111,
2024-10-26 23:16:22   code: 'ECONNREFUSED',
2024-10-26 23:16:22   syscall: 'connect',
2024-10-26 23:16:22   address: '192.168.178.111',
2024-10-26 23:16:22   port: 80,
2024-10-26 23:16:22   config: {
2024-10-26 23:16:22     url: 'http://192.168.178.111/di/v1/products/0/security',
2024-10-26 23:16:22     method: 'put',

**Comment by r1kaj** [comment]
Hey, what is the model number of your air purifier?

**Comment by NederBelg** [comment]
Hi, I have the model AC5659.
Kind regards,
Ad

**Comment by r1kaj** [comment]
I'm not really familiar with this model as I only own an AC2889/10. 
However, philips is using two different protocols (`http` & `coap`) depending on the model and firmware version. It seems like you are currently using http. You might have more luck with the coap protocol. Try changing `PHILIPS_AIR_PROTOCOL` from `http` to `coap`. 

I wasn't yet able to test the coap integration because my model only uses http. Let me know if you run into any issues.

**Comment by NederBelg** [comment]
Hi,
I get an different log, but still no succes
2024-10-27 13:22:06 philips-air-to-mqtt-1  | Firmware undefined
2024-10-27 13:22:07 philips-air-to-mqtt-1  | Connecting to MQTT
2024-10-27 13:22:07 philips-air-to-mqtt-1  | Starting Philips Air Purifier MQTT Bridge
2024-10-27 13:22:07 philips-air-to-mqtt-1  | Connecting to coap://192.168.178.12
2024-10-27 13:22:07 philips-air-to-mqtt-1  | Checking device status
2024-10-27 13:22:12 philips-air-to-mqtt-1  | Device Status undefined
2024-10-27 13:22:12 philips-air-to-mqtt-1  | Checking filter status
2024-10-27 13:22:12 philips-air-to-mqtt-1  | Error while updating device status <ref *1> Error: spawnSync python3 ETIMEDOUT
2024-10-27 13:22:12 philips-air-to-mqtt-1  |     at Object.spawnSync (node:internal/child_process:1117:20)
2024-10-27 13:22:12 philips-air-to-mqtt-1  |     at spawnSync (node:child_process:876:24)
2024-10-27 13:22:12 philips-air-to-mqtt-1  |     at Object.execFileSync (node:child_process:919:15)
2024-10-27 13:22:12 philips-air-to-mqtt-1  |     at /usr/src/app/node_modules/philips-air/dist/pyaircontrol.js:26:49
2024-10-27 13:22:12 philips-air-to-mqtt-1  |     at new Promise (<anonymous>)
2024-10-27 13:22:12 philips-air-to-mqtt-1  |     at pyaircontrol.execPromise (/usr/src/app/node_modules/philips-air/dist/pyaircontrol.js:24:16)
2024-10-27 13:22:12 philips-air-to-mqtt-1  |     at pyaircontrol.getData (/usr/src/app/node_modules/philips-air/dist/pyaircontrol.js:43:21)
2024-10-27 13:22:12 philips-air-to-mqtt-1  |     at pyaircontrol.getStatus (/usr/src/app/node_modules/philips-air/dist/pyaircontrol.js:60:21)
2024-10-27 13:22:12 philips-air-to-mqtt-1  |     at CoapClient.getStatus (/usr/src/app/node_modules/philips-air/dist/CoapClient.js:16:28)
2024-10-27 13:22:12 philips-air-to-mqtt-1  |     at updateDeviceStatus (file:///usr/src/app/dist/index.js:54:10) {
2024-10-27 13:22:12 philips-air-to-mqtt-1  |   errno: -110,
2024-10-27 13:22:12 philips-air-to-mqtt-1  |   code: 'ETIMEDOUT',
2024-10-27 13:22:12 philips-air-to-mqtt-1  |   syscall: 'spawnSync python3',
2024-10-27 13:22:12 philips-air-to-mqtt-1  |   path: 'python3',
2024-10-27 13:22:12 philips-air-to-mqtt-1  |   spawnargs: [
2024-10-27 13:22:12 philips-air-to-mqtt-1  |     '/usr/src/app/node_modules/philips-air/pyaircontrol.py',
2024-10-27 13:22:12 philips-air-to-mqtt-1  |     '--ipaddr',
2024-10-27 13:22:12 philips-air-to-mqtt-1  |     '192.168.178.12',
2024-10-27 13:22:12 philips-air-to-mqtt-1  |     '--protocol',
2024-10-27 13:22:12 philips-air-to-mqtt-1  |     'coap',
2024-10-27 13:22:12 philips-air-to-mqtt-1  |     '--status'
2024-10-27 13:22:12 philips-air-to-mqtt-1  |   ],
2024-10-27 13:22:12 philips-air-to-mqtt-1  |   error: [Circular *1],
2024-10-27 13:22:12 philips-air-to-mqtt-1  |   status: null,
2024-10-27 13:22:12 philips-air-to-mqtt-1  |   signal: 'SIGTERM',
2024-10-27 13:22:12 philips-air-to-mqtt-1  |   output: [ null, '', '' ],
2024-10-27 13:22:12 philips-air-to-mqtt-1  |   pid: 19,
2024-10-27 13:22:12 philips-air-to-mqtt-1  |   stdout: '',
2024-10-27 13:22:12 philips-air-to-mqtt-1  |   stderr: ''
2024-10-27 13:22:12 philips-air-to-mqtt-1  | }
2024-10-27 13:22:17 philips-air-to-mqtt-1  | Error while checking filter status <ref *1> Error: spawnSync python3 ETIMEDOUT
2024-10-27 13:22:17 philips-air-to-mqtt-1  |     at Object.spawnSync (node:internal/child_process:1117:20)
2024-10-27 13:22:17 philips-air-to-mqtt-1  |     at spawnSync (node:child_process:876:24)
2024-10-27 13:22:17 philips-air-to-mqtt-1  |     at Object.execFileSync (node:child_process:919:15)
2024-10-27 13:22:17 philips-air-to-mqtt-1  |     at /usr/src/app/node_modules/philips-air/dist/pyaircontrol.js:26:49
2024-10-27 13:22:17 philips-air-to-mqtt-1  |     at new Promise (<anonymous>)
2024-10-27 13:22:17 philips-air-to-mqtt-1  |     at pyaircontrol.execPromise (/usr/src/app/node_modules/philips-air/dist/pyaircontrol.js:24:16)
2024-10-27 13:22:17 philips-air-to-mqtt-1  |     at pyaircontrol.getData (/usr/src/app/node_modules/philips-air/dist/pyaircontrol.js:43:21)
2024-10-27 13:22:17 philips-air-to-mqtt-1  |     at pyaircontrol.getStatus (/usr/src/app/node_modules/philips-air/dist/pyaircontrol.js:60:21)
2024-10-27 13:22:17 philips-air-to-mqtt-1  |     at CoapClient.getStatus (/usr/src/app/node_modules/philips-air/dist/CoapClient.js:16:28)
2024-10-27 13:22:17 philips-air-to-mqtt-1  |     at CoapClient.getFilters (/usr/src/app/node_modules/philips-air/dist/CoapClient.js:22:21) {
2024-10-27 13:22:17 philips-air-to-mqtt-1  |   errno: -110,
2024-10-27 13:22:17 philips-air-to-mqtt-1  |   code: 'ETIMEDOUT',
2024-10-27 13:22:17 philips-air-to-mqtt-1  |   syscall: 'spawnSync python3',
2024-10-27 13:22:17 philips-air-to-mqtt-1  |   path: 'python3',
2024-10-27 13:22:17 philips-air-to-mqtt-1  |   spawnargs: [
2024-10-27 13:22:17 philips-air-to-mqtt-1  |     '/usr/src/app/node_modules/philips-air/pyaircontrol.py',
2024-10-27 13:22:17 philips-air-to-mqtt-1  |     '--ipaddr',
2024-10-27 13:22:17 philips-air-to-mqtt-1  |     '192.168.178.12',
2024-10-27 13:22:17 philips-air-to-mqtt-1  |     '--protocol',
2024-10-27 13:22:17 philips-air-to-mqtt-1  |     'coap',
2024-10-27 13:22:17 philips-air-to-mqtt-1  |     '--status'
2024-10-27 13:22:17 philips-air-to-mqtt-1  |   ],
2024-10-27 13:22:17 philips-air-to-mqtt-1  |   error: [Circular *1],
2024-10-27 13:22:17 philips-air-to-mqtt-1  |   status: null,
2024-10-27 13:22:17 philips-air-to-mqtt-1  |   signal: 'SIGTERM',
2024-10-27 13:22:17 philips-air-to-mqtt-1  |   output: [ null, '', '' ],
2024-10-27 13:22:17 philips-air-to-mqtt-1  |   pid: 23,
2024-10-27 13:22:17 philips-air-to-mqtt-1  |   stdout: '',
2024-10-27 13:22:17 philips-air-to-mqtt-1  |   stderr: ''
2024-10-27 13:22:17 philips-air-to-mqtt-1  | }
2024-10-27 13:22:17 philips-air-to-mqtt-1  | Filters undefined
2024-10-27 13:22:17 philips-air-to-mqtt-1  | Checking firmware status

Do you have any idea what should be changed?
Kind regards,
Ad

**Comment by r1kaj** [comment]
The communication to your air purifier is failing for some reason and I'm not sure if this is actually an issue in `philips-air-to-mqtt`. This tool is basically just bridging the air purifier to mqtt. The communication to the air purifier is done using [philips-air](https://github.com/NikDevx/philips-air) and [py-air-control](https://github.com/rgerganov/py-air-control). AFAIK `philips-air` has a native js implementation of the http protocol but is using `py-air-control` for coap.

If I was you, I would try to get the air purifier running using `py-air-control`. It supports both `http` & `coap` and apparently also `plain_coap`. If it is working using `py-air-control` it *should* also work here. I'd probably be up to provide a fix if you get it running using `py-air-control` but still have problems with `philips-air-to-mqtt`.

**Comment by NederBelg** [comment]
Hi Simon,
Thanks for letting me know. I will check out py-air-control next week.
Kind regards,
Ad

**Comment by NederBelg** [comment]
Hi Simon,
I can connect from time to time, see log
2024-11-03 12:24:22 Checking device status
2024-11-03 12:24:26 Device Status {"name":"myAirplus ","type":"AC5659","modelid":"AC5659/10","MCUBoot":true,"swversion":"2.0.0","DeviceVersion":"2.0.0","range":"MicroCube1.0","Runtime":800786,"rssi":-58,"otacheck":false,"wifilog":false,"free_memory":52104,"WifiVersion":"AWS_Philips_AIR@73.1","ProductId":"1fc3e1a2f2ac11e8a1e3061302926720","DeviceId":"3f3c9e84592411ec8a581ab7064cb1ef","StatusType":"status","ConnectType":"Online","om":"1","pwr":"1","cl":true,"aqil":0,"uil":"0","mode":"M","pm25":2,"iaql":1,"aqit":4,"aqit_ext":0,"tvoc":1,"ddp":"1","rddp":"1","err":0,"fltt1":"A3","fltt2":"C7","fltsts0":151,"fltsts1":4591,"fltsts2":4591}
2024-11-03 12:24:26 Publishing device status {"name":"myAirplus ","type":"AC5659","modelid":"AC5659/10","MCUBoot":true,"swversion":"2.0.0","DeviceVersion":"2.0.0","range":"MicroCube1.0","Runtime":800786,"rssi":-58,"otacheck":false,"wifilog":false,"free_memory":52104,"WifiVersion":"AWS_Philips_AIR@73.1","ProductId":"1fc3e1a2f2ac11e8a1e3061302926720","DeviceId":"3f3c9e84592411ec8a581ab7064cb1ef","StatusType":"status","ConnectType":"Online","om":"1","pwr":"1","cl":true,"aqil":0,"uil":"0","mode":"M","pm25":2,"iaql":1,"aqit":4,"aqit_ext":0,"tvoc":1,"ddp":"1","rddp":"1","err":0,"fltt1":"A3","fltt2":"C7","fltsts0":151,"fltsts1":4591,"fltsts2":4591}
2024-11-03 12:26:22 Checking device status
2024-11-03 12:26:26 Device Status {"name":"myAirplus ","type":"AC5659","modelid":"AC5659/10","MCUBoot":true,"swversion":"2.0.0","DeviceVersion":"2.0.0","range":"MicroCube1.0","Runtime":924497,"rssi":-59,"otacheck":false,"wifilog":false,"free_memory":52104,"WifiVersion":"AWS_Philips_AIR@73.1","ProductId":"1fc3e1a2f2ac11e8a1e3061302926720","DeviceId":"3f3c9e84592411ec8a581ab7064cb1ef","StatusType":"status","ConnectType":"Online","om":"1","pwr":"1","cl":true,"aqil":0,"uil":"0","mode":"M","pm25":3,"iaql":1,"aqit":4,"aqit_ext":0,"tvoc":1,"ddp":"1","rddp":"1","err":0,"fltt1":"A3","fltt2":"C7","fltsts0":151,"fltsts1":4591,"fltsts2":4591}
2024-11-03 12:26:26 Publishing device status {"name":"myAirplus ","type":"AC5659","modelid":"AC5659/10","MCUBoot":true,"swversion":"2.0.0","DeviceVersion":"2.0.0","range":"MicroCube1.0","Runtime":924497,"rssi":-59,"otacheck":false,"wifilog":false,"free_memory":52104,"WifiVersion":"AWS_Philips_AIR@73.1","ProductId":"1fc3e1a2f2ac11e8a1e3061302926720","DeviceId":"3f3c9e84592411ec8a581ab7064cb1ef","StatusType":"status","ConnectType":"Online","om":"1","pwr":"1","cl":true,"aqil":0,"uil":"0","mode":"M","pm25":3,"iaql":1,"aqit":4,"aqit_ext":0,"tvoc":1,"ddp":"1","rddp":"1","err":0,"fltt1":"A3","fltt2":"C7","fltsts0":151,"fltsts1":4591,"fltsts2":4591}
2024-11-03 12:28:22 Checking device status
2024-11-03 12:28:27 Device Status undefined
2024-11-03 12:30:22 Checking device status
2024-11-03 12:30:27 Device Status undefined
2024-11-03 12:32:23 Checking device status
2024-11-03 12:32:28 Device Status undefined
2024-11-03 12:34:23 Checking device status
2024-11-03 12:34:28 Device Status undefined
2024-11-03 12:36:23 Checking device status
2024-11-03 12:30:27     at spawnSync (node:child_process:876:24)
2024-11-03 12:30:27     at Object.execFileSync (node:child_process:919:15)
2024-11-03 12:30:27     at /usr/src/app/node_modules/philips-air/dist/pyaircontrol.js:26:49
2024-11-03 12:30:27     at new Promise (<anonymous>)
2024-11-03 12:30:27     at pyaircontrol.execPromise (/usr/src/app/node_modules/philips-air/dist/pyaircontrol.js:24:16)
2024-11-03 12:30:27     at pyaircontrol.getData (/usr/src/app/node_modules/philips-air/dist/pyaircontrol.js:43:21)
2024-11-03 12:30:27     at pyaircontrol.getStatus (/usr/src/app/node_modules/philips-air/dist/pyaircontrol.js:60:21)
2024-11-03 12:30:27     at CoapClient.getStatus (/usr/src/app/node_modules/philips-air/dist/CoapClient.js:16:28)
2024-11-03 12:30:27     at updateDeviceStatus (file:///usr/src/app/dist/index.js:54:10) {
2024-11-03 12:30:27   errno: -110,
2024-11-03 12:30:27   code: 'ETIMEDOUT',
2024-11-03 12:30:27   syscall: 'spawnSync python3',
2024-11-03 12:30:27   path: 'python3',
2024-11-03 12:30:27   spawnargs: [
2024-11-03 12:30:27     '/usr/src/app/node_modules/philips-air/pyaircontrol.py',
2024-11-03 12:30:27     '--ipaddr',
2024-11-03 12:30:27     '192.168.178.12',
2024-11-03 12:30:27     '--protocol',
2024-11-03 12:30:27     'coap',
2024-11-03 12:30:27     '--status'
2024-11-03 12:30:27   ],
2024-11-03 12:30:27   error: [Circular *1],
2024-11-03 12:30:27   status: null,
2024-11-03 12:30:27   signal: 'SIGTERM',
2024-11-03 12:30:27   output: [ null, '', '' ],
2024-11-03 12:30:27   pid: 68,
2024-11-03 12:30:27   stdout: '',
2024-11-03 12:30:27   stderr: ''
2024-11-03 12:30:27 }

I can connect with the python app: aioairctrl to retrieve the status. However it can take up to 2 minutes before I get a response. But there is always a response. 
The status-obser can take some time to connect for the first time. After that it shows immediately the changes in the status. With the commands I have more luck and I can change the fan speed and turn it off/on without any problem.

I have two questions
1) Do you have any idea what makes the connection so unstable?
2) What would be the MQTT messages to turn off/on and change the speed?

Kind regards,
Ad

**Comment by NederBelg** [comment]
Hi, I got it all to work with aioairctrl. I already had an MQTT server running so I pickup the messages send from my homeserver for the Airplus and forwarded these to aioairctrl. The same I did the other way around with the status messages.
Thanks for answering my initial questions, without those answers I wouldn't have found the solution.

**Comment by NederBelg** [comment]
Hi, I got it all to work with aioairctrl. I already had an MQTT server running so I pickup the messages send from my homeserver for the Airplus and forwarded these to aioairctrl. The same I did the other way around with the status messages.
Thanks for answering my initial questions, without those answers I wouldn't have found the solution.

**Comment by r1kaj** [comment]
Glad to hear you've got it running. Sorry for not replying to your previous comment. I was really busy the past few days, but I will add the MQTT commands to the documentation when I get to it.
